name: iOS TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-submit:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i -g eas-cli

      - run: npm ci

      - run: npx --yes eas-cli whoami
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Build
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build -p ios --profile production --non-interactive

      - name: Submit
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas submit -p ios --latest --non-interactive --asc-app-id ${{ secrets.ASC_APP_ID }}
